# Generated by Django 2.2.28 on 2022-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
