# Generated by Django 3.2.16 on 2023-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_todo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_or_phone', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=2000)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
