# Generated by Django 3.2.16 on 2023-04-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title English')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Russian')),
                ('title_hy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Armenian')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_ru', models.TextField(verbose_name='Description Russian')),
                ('description_hy', models.TextField(verbose_name='Description Armenian')),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
                ('main_image', models.ImageField(upload_to='media/slider', verbose_name='Main Image')),
                ('blur_image', models.ImageField(upload_to='media/slider', verbose_name='Blur Image')),
            ],
        ),
    ]
