# Generated by Django 3.2.16 on 2023-04-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
