# Generated by Django 3.2.16 on 2023-05-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_product_shop_url'),
        ('core', '0008_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('not_paid', 'Not Paid'), ('accepted', 'Accepted'), ('in_process', 'In Process'), ('shipping', 'Shipping'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=255, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title English')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Russian')),
                ('title_hy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Armenian')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_ru', models.TextField(verbose_name='Description Russian')),
                ('description_hy', models.TextField(verbose_name='Description Armenian')),
                ('image', models.ImageField(upload_to='media/slider', verbose_name='Main Image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('states_available', models.ManyToManyField(related_name='states', to='users.State')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
