# Generated by Django 3.2.16 on 2023-05-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_orderitem_shippingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orders', to='core.shippingmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Shipping Price'),
        ),
    ]
