# Generated by Django 3.2.16 on 2023-05-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_background'),
        ('core', '0010_auto_20230507_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orders', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('accepted', 'Accepted'),
                                            ('in_process', 'In Process'), ('shipping', 'Shipping'),
                                            ('done', 'Done'), ('cancelled', 'Cancelled'),
                                            ('refunded', 'Refunded')], max_length=255, verbose_name='status'),
        ),
    ]
