# Generated by Django 3.2.16 on 2023-06-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productauthor_productgame'),
        ('core', '0013_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('accepted', 'Accepted'), ('in_process', 'In Process'), ('shipping', 'Shipping'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='product.product'),
        ),
    ]
