# Generated by Django 3.2.16 on 2024-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230604_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('star', models.PositiveSmallIntegerField(default=5)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
