# Generated by Django 3.2.16 on 2024-03-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240310_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
