# Generated by Django 3.2.16 on 2025-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_review_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
