BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBB gettext(u'Generate Sketch')  BBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXX
    XXXXXX
    BB BBBBBBBB
        XXXX  XXXXXXXXXXXXXXX
            XXXX XXXXXXX XXXXXXXXXXXXXXX
        XXXXXX
    BBBBB
XXXXXX
BBBBBBBB