# Generated by Django 4.1.5 on 2023-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(default=1, upload_to='audios/'),
            preserve_default=False,
        ),
    ]
