# Generated by Django 4.1.5 on 2023-01-21 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0002_audio_audio'),
    ]
    operations = [
        migrations.AddField(
            model_name='author',
            name='quote_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='quote_hy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='quote_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),

    ]
