# Generated by Django 4.1.5 on 2023-01-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0003_product_productcategory_author_quote_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='slug',
            field=models.SlugField(default=3121111, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=3121111, unique=False),
            preserve_default=False,
        ),
    ]
