# Generated by Django 4.1.5 on 2023-01-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0004_product_productcategory_audio_slug_author_slug_and_more'),
    ]

    operations = [
    ]
