# Generated by Django 4.1.5 on 2023-01-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0005_product_productcategory_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        )
    ]
