# Generated by Django 3.2.16 on 2023-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='middle_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/middle_optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/thumb/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='game',
            name='middle_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/middle_optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='game',
            name='optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/thumb/', verbose_name='Thumbnail'),
        ),
    ]
