# Generated by Django 3.2.16 on 2023-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0002_auto_20230604_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
