# Generated by Django 3.2.16 on 2023-11-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0003_auto_20230604_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='game/'),
        ),
    ]
