# Generated by Django 3.2.16 on 2023-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0004_author_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
