# Generated by Django 3.2.16 on 2024-05-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0005_author_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('short_hy', models.CharField(max_length=2000)),
                ('short_en', models.CharField(max_length=2000)),
                ('short_ru', models.CharField(max_length=2000)),
                ('description_hy', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='game/')),
                ('seen_count', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('optimized', models.ImageField(blank=True, null=True, upload_to='media/product/optimized', verbose_name='Image')),
                ('middle_optimized', models.ImageField(blank=True, null=True, upload_to='media/product/middle_optimized', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/product/thumb/', verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_hy', models.CharField(max_length=2000)),
                ('short_en', models.CharField(max_length=2000)),
                ('short_ru', models.CharField(max_length=2000)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_item', to='core_game.game')),
            ],
        ),
    ]
