# Generated by Django 3.2.16 on 2024-05-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0006_blogitem_canvasblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_item', to='core_game.canvasblog'),
            preserve_default=False,
        ),
    ]
