# Generated by Django 3.2.16 on 2026-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title_hy']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title_hy']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_status_b23d34_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'),
        ),
    ]
