# Generated by Django 3.2.16 on 2026-03-10

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20260310_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt_hy',
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name=_('Excerpt Armenian'),
            ),
        ),
    ]
