# Generated by Django 3.2.16 on 2026-03-11 06:48

from django.db import migrations, models

try:
    from tinymce.models import HTMLField
except ImportError:
    HTMLField = models.TextField


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_share_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postview',
            name='blog_post_vi_post_id_89c828_idx',
        ),
        migrations.RemoveIndex(
            model_name='postview',
            name='blog_post_vi_viewed__d54536_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt_hy',
            new_name='excerpt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_hy',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_hy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=HTMLField(default='-', verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(
                fields=['post', 'domain'],
                name='blog_post_v_post_id_6d9436_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(
                fields=['viewed_date'],
                name='blog_post_v_viewed__367e77_idx',
            ),
        ),
    ]
