BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Yatuk') XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXX XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Login to Yatuk CMS system') XXXXX
                XXXXX XXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXXX gettext(u'Username')  XXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFF FFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXX gettext(u'Password')  XXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFF FFFFFFFF
                  XXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX gettext(u'Login') XXXXXXXXX
                  XXXXXX
                XXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXX XXX
        XXXXXX
        XXXX XXX XXXX XXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXX XXXXXXXXX XXX
    XXXX XXXXXX XX XXX XXXX XXXX XXX
    XXXX XXX XXXXXX XX XXX XXXX XXXX XXX
    XXXX XXXXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXXX
XXXXXXX