XXXXXXXXX XXXXX
BBBB BBBB
BBBB BBBBBB
XXXXX XXXXXXXXXX
  XXXXXX
    XXXX XXXXXXXX XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX    
    XXXX XXXXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXX XXX
    XXXX XXXXXX XXX XXX XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXX XXXXXX XXX XXX XXXX XXXX XXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXX XXX
    XXXX XXXXXX XXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
    XXXX XXX XXXXXX XXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
    XXXXXXXBBBBB BBBBBBBBBBBBB X  gettext(u'Yatuk') XXXXXXXX
  XXXXXXX

XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBB
      XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XX
XXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXX XXXXXXXXX XXX
  XXXX XXXXXX XX XXX XXXX XXXX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXX XXX XXXXXX XX XXX XXXX XXXX XXX
  XXXX XXXXXXXXX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXX XXXXXXXXX XXX
  XXXX XXXXXX XX XXX XXXX XXXX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXX XXXXXX XX XXX XXXX XXXX XXX
XXXXXXX
BBBBB BBBBBBBBBBBBBBBBBB BBBBBBBB
XXXXXXX

