# Generated by Django 2.2.28 on 2022-10-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_hy', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_en', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_hy', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_hy', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCaegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_hy', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_hy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/product')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/product/thumb/')),
                ('is_main', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
