# Generated by Django 2.2.28 on 2022-10-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221008_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product'),
        ),
    ]
