# Generated by Django 2.2.28 on 2022-10-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221008_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_hy', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_hy', models.TextField()),
                ('address_en', models.CharField(max_length=255)),
                ('address_ru', models.CharField(max_length=255)),
                ('address_hy', models.CharField(max_length=255)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('collaborator', 'collaborator'), ('gift', 'Gift'), ('other', 'Other')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='product.Collaborator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='product.Product')),
            ],
        ),
    ]
