# Generated by Django 2.2.28 on 2022-10-08 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20221008_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
