# Generated by Django 2.2.28 on 2022-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producttransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
