# Generated by Django 2.2.28 on 2022-10-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20221008_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='product.Collaborator'),
        ),
    ]
