# Generated by Django 2.2.28 on 2022-10-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20221008_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('direct', 'Ուղղակի'), ('indirect', 'Անուղղակի')], max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_hy', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_hy', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/icon')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductCaegory',
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='type',
            field=models.CharField(choices=[('website', 'Վեբ կայք'), ('facebook', 'Ֆեյսբուք'), ('collaborator', 'Համագործակից'), ('gift', 'Նվեր'), ('other', 'Այլ')], max_length=255),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='product.ProductCategory'),
        ),
    ]
