# Generated by Django 2.2.28 on 2022-10-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20221009_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costtransaction',
            name='product_category',
        ),
    ]
