# Generated by Django 2.2.28 on 2022-10-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtransaction',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='product.ProductCategory'),
        ),
    ]
