# Generated by Django 2.2.28 on 2022-10-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_costtransaction_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
