# Generated by Django 3.2.16 on 2022-12-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='address_en',
            field=models.CharField(max_length=255, verbose_name='Address English'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='address_hy',
            field=models.CharField(max_length=255, verbose_name='Address Armenian'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='address_ru',
            field=models.CharField(max_length=255, verbose_name='Address Russian'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='description_en',
            field=models.TextField(verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='description_hy',
            field=models.TextField(verbose_name='Description Armenian'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='description_ru',
            field=models.TextField(verbose_name='Description Russian'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title English'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='title_hy',
            field=models.CharField(max_length=255, verbose_name='Title Armenian'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Title Russian'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='product.productcategory', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_hy',
            field=models.TextField(verbose_name='Description Armenian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(verbose_name='Description Russian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_hy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug Armenian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug Russian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_hy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Armenian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Russian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_count',
            field=models.IntegerField(default=50, verbose_name='Total Count'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_hy',
            field=models.TextField(verbose_name='Description Armenian'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description_ru',
            field=models.TextField(verbose_name='Description Russian'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title English'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_hy',
            field=models.CharField(max_length=255, verbose_name='Title Armenian'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Title Russian'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/product', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Is Main'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/thumb/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='product.collaborator', verbose_name='Collaborator'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Crated At'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('collaborator', 'Collaborator'), ('gift', 'Gift'), ('other', 'Other')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='product.collaborator', verbose_name='Collaboratir'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='product.product', verbose_name='Product'),
        ),
    ]
