# Generated by Django 3.2.16 on 2023-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
