# Generated by Django 3.2.16 on 2023-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product', verbose_name='Image'),
        ),
    ]
