# Generated by Django 3.2.16 on 2023-06-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productimage_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='middle_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/middle_optimized', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/optimized', verbose_name='Image'),
        ),
    ]
