# Generated by Django 3.2.16 on 2023-06-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0001_initial'),
        ('product', '0018_auto_20230601_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core_game.game')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='core_game.author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_authors', to='product.product')),
            ],
        ),
    ]
