# Generated by Django 3.2.16 on 2023-06-10 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230604_1713'),
        ('product', '0019_productauthor_productgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 15, 33, 59, 227489), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name='Description English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_hy',
            field=tinymce.models.HTMLField(verbose_name='Description Armenian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=tinymce.models.HTMLField(verbose_name='Description Russian'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 15, 33, 59, 227489), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 15, 33, 59, 227489), verbose_name='Date'),
        ),
    ]
