# Generated by Django 3.2.16 on 2023-06-17 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20230610_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='for_share',
            field=models.BooleanField(default=False, verbose_name='For Share'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 17, 19, 37, 36, 698247), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is Main'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 17, 19, 37, 36, 697248), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 17, 19, 37, 36, 707355), verbose_name='Date'),
        ),
    ]
