# Generated by Django 3.2.16 on 2023-06-18 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20230617_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 18, 47, 13, 641368), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 18, 47, 13, 641368), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 18, 47, 13, 652412), verbose_name='Date'),
        ),
    ]
