# Generated by Django 3.2.16 on 2023-06-18 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20230618_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 18, 49, 43, 842516), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 18, 49, 43, 841513), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 18, 18, 49, 43, 842516), verbose_name='Date'),
        ),
    ]
