# Generated by Django 3.2.16 on 2023-07-01 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20230618_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/sketch', verbose_name='Image')),
                ('sketch', models.ImageField(upload_to='media/sketch/sketch', verbose_name='Sketch Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/sketch/thumb/', verbose_name='Thumbnail')),
            ],
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 16, 55, 36, 50364), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 16, 55, 36, 50364), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 16, 55, 36, 50364), verbose_name='Date'),
        ),
    ]
