# Generated by Django 3.2.16 on 2023-07-02 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20230701_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug_hy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 20, 19, 2, 2402), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 20, 19, 2, 2402), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sketchimage',
            name='sketch',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sketch Image'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 20, 19, 2, 17418), verbose_name='Date'),
        ),
    ]
