# Generated by Django 3.2.16 on 2023-09-10 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20230909_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 10, 40, 59, 342539), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 10, 40, 59, 342539), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 10, 40, 59, 343539), verbose_name='Date'),
        ),
    ]
