# Generated by Django 3.2.16 on 2023-09-10 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20230910_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 11, 0, 33, 776879), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 11, 0, 33, 775878), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 11, 0, 33, 776879), verbose_name='Date'),
        ),
    ]
