# Generated by Django 3.2.16 on 2023-11-28 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20231118_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 14, 35, 667087), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 14, 35, 667087), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 14, 35, 667087), verbose_name='Date'),
        ),
    ]
