# Generated by Django 3.2.16 on 2023-12-10 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20231128_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 17, 51, 45, 328706), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 17, 51, 45, 328706), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 17, 51, 45, 328706), verbose_name='Date'),
        ),
    ]
