# Generated by Django 3.2.16 on 2026-03-11 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20260310_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 11, 10, 47, 52, 317120), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 11, 10, 47, 52, 317120), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 11, 10, 47, 52, 317120), verbose_name='Date'),
        ),
    ]
