BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Total') XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX X XXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        BBBBBB
    XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B BXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'And %(count)s other products ') SSS SSSSSSSSS SSSSS SSSSSSSS XXXXXXBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXX gettext(u'View Cart') XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Checkout') XXXXXXXXXXXXX
    XXXXXX
    BBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u"Choose your favorite product and add it to the cart. I don't like to be empty") XXXXXX
    BBBBB
XXXXXX