XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX  XXXXXXXXBBB BBBBBBBBBBBBBBBBX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX
        XXXXXX 
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX  XXXXXXXXBBB BBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
        XXXXXX
    XXXXXX
XXXXXX