BBBB BBBB
BBBB BBBBBB
XXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBB
        XXXXXX
        XX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX  XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX gettext(u'Yatuk jigsaw puzzle') XX
            XXXX XXXXXXXXXXXXXX gettext(u'Yatuk') XXXXXX
        XXXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXBB BBBBBB BB BBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXXXXXXX
            XXXXXX XXXXXXXBB BBBBBB BB BBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBXX gettext(u'Store') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBB BB BBBBBB BB BBBBBBBBBBBB BB BBBBBB BB BBBBBBBBBXXXXXXBBBBBX X
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBB BB BBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBXX gettext(u'Authors') XXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBXX gettext(u'Shipping') XXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBB BB BBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBXX
                     gettext(u'Contact Us') XXXXXXXXX
                XXXXX
            XXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'My Profile') XXXXXXXXX
            BBBB
            XXXXXX XXXXXXXBB BBBBBB BB BBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBXX gettext(u'Login') XXXXXXXXX
            BBBBB
            XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBB  BBBB BBBBBBBBBBBBXXXXXX
                BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                  XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                XXXXXX 
                  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBB BB BBBBBBBBB
                    BB BBBBBBBBB BB BBBBBBBBBBBBBB
                      XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX XXXXXXXXXXXXXXX  XXXX
                    BBBBB
                  BBBBBB
                  XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX 
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  BBB BBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXBBBBBX XXXXXXXX XXXXXXXXBBB BBBBBBBBBBBXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                      XXXX
                BBBBBB
                XXXXXX
            XXXXX
          XXXXX
        XXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
