# Generated by Django 3.2.16 on 2023-08-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_game', '0003_auto_20230604_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('bio_hy', models.TextField(blank=True, null=True)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_ru', models.TextField(blank=True, null=True)),
                ('dates', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='authors/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimized', models.ImageField(blank=True, null=True, upload_to='media/product/optimized', verbose_name='Image')),
                ('middle_optimized', models.ImageField(blank=True, null=True, upload_to='media/product/middle_optimized', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/product/thumb/', verbose_name='Thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hy', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('content_hy', models.TextField()),
                ('content_en', models.TextField()),
                ('content_ru', models.TextField()),
                ('view_count', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poem.author')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='core_game.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poem.genre')),
            ],
        ),
        migrations.CreateModel(
            name='PoemLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poem.label')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='poem.poem')),
            ],
        ),
    ]
