# Generated by Django 3.2.16 on 2023-08-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0003_auto_20230604_1735'),
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poems', to='core_game.game'),
        ),
    ]
