# Generated by Django 3.2.16 on 2023-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_alter_poem_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
