# Generated by Django 3.2.16 on 2023-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_auto_20230801_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
