# Generated by Django 3.2.16 on 2023-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_alter_poem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
