# Generated by Django 3.2.16 on 2023-08-02 12:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_author_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_hy',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
