# Generated by Django 3.2.16 on 2023-08-02 12:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_auto_20230802_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content_hy',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
