# Generated by Django 3.2.16 on 2023-08-07 08:16

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_auto_20230802_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=2)),
                ('name_hy', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('content_hy', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_en', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_ru', tinymce.models.HTMLField(blank=True, null=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='poem.poem')),
            ],
        ),
    ]
