# Generated by Django 3.2.16 on 2023-09-01 14:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_auto_20230827_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio_hy',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio_ru',
        ),
        migrations.CreateModel(
            name='AuthorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_hy', tinymce.models.HTMLField(blank=True, null=True)),
                ('bio_en', tinymce.models.HTMLField(blank=True, null=True)),
                ('bio_ru', tinymce.models.HTMLField(blank=True, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='poem.author')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_hy', tinymce.models.HTMLField(blank=True, null=True)),
                ('bio_en', tinymce.models.HTMLField(blank=True, null=True)),
                ('bio_ru', tinymce.models.HTMLField(blank=True, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='poem.author')),
            ],
        ),
    ]
