# Generated by Django 3.2.16 on 2023-09-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0002_auto_20230618_1850'),
        ('core_game', '0003_auto_20230604_1735'),
        ('poem', '0011_poemcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimized', models.ImageField(blank=True, null=True, upload_to='media/photo/optimized', verbose_name='Image')),
                ('middle_optimized', models.ImageField(blank=True, null=True, upload_to='media/photo/middle_optimized', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/photo/thumb/', verbose_name='Thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core_play.author')),
                ('painter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core_game.author')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='poem.photo')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='poem.author')),
            ],
        ),
    ]
