# Generated by Django 3.2.16 on 2023-09-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0012_photo_photoperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
