# Generated by Django 3.2.16 on 2023-09-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0013_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
