# Generated by Django 3.2.16 on 2023-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0014_alter_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='background_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=255),
        ),
    ]
