# Generated by Django 3.2.16 on 2023-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0015_photo_background_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
