# Generated by Django 3.2.16 on 2023-11-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0002_auto_20230618_1850'),
        ('core_game', '0004_author_main_image'),
        ('poem', '0016_alter_poem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core_play.audio'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core_game.game'),
        ),
        migrations.AddField(
            model_name='like',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core_play.audio'),
        ),
        migrations.AddField(
            model_name='like',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core_game.game'),
        ),
        migrations.AddField(
            model_name='poemcomment',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core_play.audio'),
        ),
        migrations.AddField(
            model_name='poemcomment',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='poem.poem'),
        ),
        migrations.AlterField(
            model_name='like',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='poem.poem'),
        ),
        migrations.AlterField(
            model_name='poemcomment',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poem.poem'),
        ),
    ]
