# Generated by Django 3.2.16 on 2023-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0017_auto_20231118_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
