BBBB BBBB
BBBB BBBBBB
XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
  XXXXXX
  XXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Main') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'To Do List') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Orders') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Products') XXXXXXX
      XXXX
    XXXXX

    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Sales') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Costs') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXX XXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Transfers') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Collaaborators') XXXXXXX
      XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Contact Form List') XXXXXXX
      XXXX
    XXXXX

  XXXXX
XXXXXX
XXXX XXXXXXXXXXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXX

    XXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
      BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
      BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
      BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBBBBB

      XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          FFFFF
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBB BBBB BB BBBBBBBBB
          BB BBBBBBBBB BB BBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXXXXXXXXX 
          XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXX
          FFFFFXXXXBBBBB
          BBBBBB
        XXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX 
            XXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
            XX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
                 
              BBBB
                
              BBBBB
            XXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Logout') XXXX
            XXXXXX
          XXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXX
    XXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
XXXXXX