BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX
        BBB BBBBBBB BB BBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XX X X XXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        BBBBBB
      XXXXXX

    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBX 
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX gettext(u'Add new address') XXXXXXXXX
  XXXXXX