BBBB BBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX
      XXXX gettext(u'Sign in') XXXXX
      BBBBBBBBBB
      BBB BBBBB BB BBBB
      XXXX XXXXXXXXXXXXXXXXXXX
        
        
        BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
      XXXXXX
    BBBBBB
    XXXXXXX XXXXXXXXXXXXXX gettext(u'Log In') XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Dont have an account?')  XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        X gettext(u'Sign up') XXXX XXXXXX gettext(u'now!') XXXXXXX
      XXXXXX
  XXXXXXX
XXXXXX
