BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBB
      XXXXXX
    XXXXXX
XXXXXX
