BBBB BBBB
XXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'First Name:') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Last Name:') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX gettext(u'Email:') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Phone Number:') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX        XXXXXX
      
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Username:') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX 
          XXXXXXXXBBB BBBBBBBBBBBX
          XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX gettext(u'Edit') XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
