BBBB BBBBBB
BBBB BBBB
XXXX XXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBB BB BBBBBBBBBBBBBBBXXXXXXXXXBBBBBXX gettext(u'Personal details') XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBB BB BBBBBBBBBBBXXXXXXXXXBBBBBXX gettext(u'Addresses') XXXXXXXXX
      BB BBBBBB
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBB BB BBBBBBBBXXXXXXXXXBBBBBXX gettext(u'Orders') XXXXXXXXX
      BBBBB
      XXXXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Logout') XXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Personal details') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBXXXXXXXXXBBBBBX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Addresses') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX

      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBXXXXXXXXXBBBBBX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Orders') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXX
  XXXXXX  XXXXXX
