BBBB BBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    BBB BBBBB BB BBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
      
      
      BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXX
  BBBBBB
  XXXX XXXXXXXXXXXXX XXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXBBB BBBBBBBBBBBX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
      X gettext(u'Save') XXXXXXXXX
      XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXBBB BBBBBBBBBX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
      X gettext(u'Cancel') XXXXXXXXX
  XXXXXX
  XXXXXXX
XXXXXX
