BBBB BBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX
    XXXX gettext(u'Sign up') XXXXX
    BBBBBBBBBB
    BBB BBBBB BB BBBB
      XXXX XXXXXXXXXXXXXXXXXXX
        
        
        BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
      XXXXXX
    BBBBBB
    XXXXXXX XXXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX gettext(u'Already have an account?')  XXXXXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
      X gettext(u'Sign in') XXXX
    XXXXXX
  XXXXXXX
XXXXXX
