# Generated by Django 3.2.16 on 2023-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='middle_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors/middle_optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='audio',
            name='optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors/optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='audio',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors/thumb/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='author',
            name='middle_optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors/middle_optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='optimized',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors/optimized', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/authors/thumb/', verbose_name='Thumbnail'),
        ),
    ]
