BBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'New Selling') XXXXXXXXXXX
XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
  BBBBBBBBBB
  
  
  XXXXXX  XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX gettext(u'Save') XX
XXXXXXX
XXXXXX
XXXXXX
XXXXXX
