BBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'New Transfer') XXXXX
      XXXXXX
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX  XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX