BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX gettext(u'Shopping Cart') XXXXX
        XXXXXX gettext(u'You have made a wonderful choice. Please make sure the quantity of products is exactly what you need.') XXXXXXX
    XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
XXXXXX
XXXXXX
BBBBBBBB BBBBBBB