BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Checkout') XXXXX
            XXXXXX gettext(u'Please fill all the fields in correct way.') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
