BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXX XXX XXXXXXXXX XXXXXXX
    XXXXXXX gettext(u'Yatuk')  X  gettext(u'Contact Us') XXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX
BBBBBBBB BBBBBBB