BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBB gettext(u'Costs') BBBBBBBB
X
BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Costs') XXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXBBB BBBBBBBBBB XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Cost') XXXXXXXXX
      XXXXXX
      XXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Filters') XX XXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXX

      XXXX
      XXXX XXXXXXXXXXXXXXX BB BBBBBBBB BB BBBBB BB BBBBBBBBB BB BBBBB  BB BBBBBB BB BBXXXXBBBBBX
        XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Product Type') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXX BB BBBBBBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
              BBB BBBBBBBBB BB BBBBBBBBBB
              XXXXXXX XXXXXXXX BB BBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
                XXXXXXXXX
              BBBBBB
            XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Type') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXX BB BBBBBBBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
              BBB BB BB BBBBBBBBBB
              XXXXXXX XXXXXXXX BB BBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
              BBBBBB
            XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX gettext(u'Search') XXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXBBB BBBBBBBX
              XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB