BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Transfers')  BBBBBBBB
X
BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX
          BBBBBBBBBB
          FFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF
          XXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXBBB BBBBBBBBBBBBBBBBBX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Generate') XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX

BBBBBBBB