BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBB gettext(u'Main') BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Total Sales') XXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXBB BBBBBBBBBBBBBBB B BXXXXXXXXXXXXBBBBXXXXXXXXXXXBBBBB 
                     XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB B B
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX  XX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBB
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u"Last 30 day's Sales") XXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Total Costs') XXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXBB BBBBBBBBBBBBBBB B BXXXXXXXXXXXBBBBXXXXXXXXXXXXBBBBB 
                      XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB B B
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBB
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u"Last 30 day's costs") XXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Sales by routes') XXXXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Costs by Types') XXXXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u"Last 1 year's Sales") XXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u"Last 1 year's costs") XXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX


XXXXXX

BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
  XXX XXXXXXX X X
    XXXXXXX X
      XXXXXX XX
        XXXXXX X
          XXXXXXXXXXXX XXXX
        XX
        XXXXXXXXXX X
          XXXXXX XXXXXXXXXX XXXX XXXXXXXXX
        X
      XXX
      XXXXXX XX
        XXXXXXXXXX X
          XXXXXX XXXXXXXXXX XXXX XXXXXXXXX
        X
      XX
    XX
    XXXXXXX X
      XXXXXXXX XXXXX
    XX
    XXXXXXXXX X
      XXXXXX X
        XXXXXXX X
      X
    X
  XX

  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXXXX
      XXXXX FFFFX
      XXXXXXXX XXXXXXX
    XXX
  X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXXXX
      XXXXX FFFFX
      XXXXXXXX XXXXXXX
    XXX
  X
  XXXXXXXXXXXX X XXXXXXXX XX X
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXX XXXXXXXXXXXXXXXXXX X X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXX X
      XXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXX
    X
  XX

  XX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXXX
      XXXXX FFFFX
      XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX
  X
  XX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXXX
      XXXXX FFFFX
      XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX
  X
XXXXXXXXX
BBBBBBBB