BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Privacy Policy') XXXXX
            XXXXXX gettext(u'Updated at 2023-05-30') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Yatuk (“we,” “our,” or “us”) is committed to protecting your privacy.\n            This Privacy Policy explains how your personal information is collected, used, and disclosed by Yatuk.\n            This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our \n            application, Yatuk. By accessing or using our Service, you signify that you have read, understood,\n            and agree to our collection, storage, use, and disclosure of your personal information as described\n             in this Privacy Policy and our Terms of Service. This Privacy Policy was created with Termify.\n            ') 
            SSSSS SSSSSS SSSSSS SS SSSSS SS SSSSSSSSS SS SSSSSSSSSS SSSS SSSSSSSS
            SSSS SSSSSSS SSSSSS SSSSSSSS SSS SSSS SSSSSSSS SSSSSSSSSSS SS SSSSSSSSSS SSSSS SSS SSSSSSSSS SS SSSSSS
            SSSS SSSSSSS SSSSSS SSSSSSS SS SSS SSSSSSSS SSS SSS SSSSSSSSSS SSSSSSSSSS SSSSSSSSSSSSSS SSS SSSSSSSSSS SSSSSSSSS SSS 
            SSSSSSSSSSSS SSSSSS SS SSSSSSSSS SS SSSSS SSS SSSSSSSS SSS SSSSSSS SSSS SSS SSSS SSSSS SSSSSSSSSSS
            SSS SSSSS SS SSS SSSSSSSSSSS SSSSSSSS SSSS SSS SSSSSSSSSS SS SSSS SSSSSSSS SSSSSSSSSSS SS SSSSSSSSS
             SS SSSS SSSSSSS SSSSSS SSS SSS SSSSS SS SSSSSSSS SSSS SSSSSSS SSSSSS SSS SSSSSSS SSSS SSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX  XXXXXX
            XXXX gettext(u'Definitions and key terms') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XXXX
                XXXX gettext(u'Cookie:&nbsp;small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.') SSSSSSSSSSSSSSSSSS SSSSSS SS SSSS SSSSSSSSS SS S SSSSSSS SSS SSSSS SS SSSS SSS SSSSSSSS SS SS SSSS SS SSSSSSSS SSSS SSSSSSSS SSSSSSS SSSSSSSSSS SSSSSSSS SSSSSSSSSSS SSSSS SSS SSSS SS SSSS SSSSSSSS SSSSSSSSSS SS SSSSS SSSSSSSSSSSSXXXXX
                XXXX gettext(u'Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Yatuk, Armenia, Shirak, Akhuryan, Petros Mkhoyan 1 line 7 building that is responsible for your information under this Privacy Policy.') SSSSSSSS SSSS SSSS SSSSSS SSSSSSSS SSSSSSSSSS SSSSS SSSSS SS SSSSSS SS SSSSSS SS SSSSSS SSSSSSSS SSSSSSS SSSSSSSSS SSSSSS SSSSSSS S SSSS S SSSSSSSS SSSS SS SSSSSSSSSSS SSS SSSS SSSSSSSSSSS SSSSS SSSS SSSSSSS SSSSSSSXXXXX
                XXXX gettext(u'Country: where Yatuk or the owners/founders of Yatuk are based, in this case is Armenia') SSSSSSSS SSSSS SSSSS SS SSS SSSSSSSSSSSSSSS SS SSSSS SSS SSSSSS SS SSSS SSSS SS SSSSSSSXXXXX
                XXXX gettext(u'Customer:&nbsp;refers to the company, organization or person that signs up to use the Yatuk Service to manage the relationships with your consumers or service users.') SSSSSSSSSSSSSSSSSSSSS SS SSS SSSSSSSS SSSSSSSSSSSS SS SSSSSS SSSS SSSSS SS SS SSS SSS SSSSS SSSSSSS SS SSSSSS SSS SSSSSSSSSSSSS SSSS SSSS SSSSSSSSS SS SSSSSSS SSSSSSXXXXX
                XXXX gettext(u'Device:&nbsp;any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Yatuk and use the services.') SSSSSSSSSSSSSSSS SSSSSSSS SSSSSSSSS SSSSSS SSSS SS S SSSSSS SSSSSSS SSSSSSSS SS SSS SSSSS SSSSSS SSSS SSS SS SSSS SS SSSSS SSSSS SSS SSS SSS SSSSSSSSSXXXXX
                XXXX gettext(u'IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.') SS SSSSSSSS SSSSS SSSSSS SSSSSSSSS SS SSS SSSSSSSS SS SSSSSSSS S SSSSSS SSSSS SS SS SSSSSSSS SSSSSSSS SSSS SSSSSSSS SSSSS SSSSSSS SSS SSSSSSS SSSSSSSS SS SSSSSSSSSS SSSSSSS SS SS SSSSSSS SSS SSSSS SS SSSS SS SSSSSSSS SSS SSSSSSSS SSSS SSSSS S SSSSSS SS SSSSSSSSSS SS SSS SSSSSSSSSXXXXX
                XXXX gettext(u'Personnel:&nbsp;refers to those individuals who are employed by Yatuk or are under contract to perform a service on behalf of one of the parties.') SSSSSSSSSSSSSSSSSSSSSS SS SSSSS SSSSSSSSSSS SSS SSS SSSSSSSS SS SSSSS SS SSS SSSSS SSSSSSSS SS SSSSSSS S SSSSSSS SS SSSSSS SS SSS SS SSS SSSSSSSSXXXXX
                XXXX gettext(u'Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.') SSSSSSSS SSSSS SSS SSSSSSSSSSS SSSS SSSSSSSSS SSSSSSSSSSS SS SS SSSSSSSSSS SSSS SSSSS SSSSSSSSSSS S SSSSSSSSS S SSSSSSSS SSSSSSSSSSSSSS SSSSSS S SSSSSS SSS SSS SSSSSSSSSSSSSS SS SSSSSSSSSSSSSSS SS S SSSSSSS SSSSSSSXXXXX
                XXXX gettext(u'Service: refers to the service provided by Yatuk as described in the relative terms (if available) and on this platform.') SSSSSSSS SSSSSS SS SSS SSSSSSS SSSSSSSS SS SSSSS SS SSSSSSSSS SS SSS SSSSSSSS SSSSS SSS SSSSSSSSSS SSS SS SSSS SSSSSSSSSXXXXX
                XXXX gettext(u'Third-party service:&nbsp;refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.') SSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSSSS SSSSSSS SSSSSSSSS SSSSSSSSSSS SSS SSSSSSSSS SSSSSSSSS SSS SSSSSS SSS SSSSSSS SSS SSSSSSS SS SSSSS SSSSSSSS SS SSSSSSSS SS SSSSS SSS SSSSSSSS SSSSXXXXX
                XXXX gettext(u'Website: Yatuk’s site, which can be accessed via this URL: https://yatuk.am/') SSSSSSSS SSSSSSS SSSSS SSSSS SSS SS SSSSSSSS SSS SSSS SSSS SSSSSSSSSSSSSSSSSXXXXX
                XXXX gettext(u'You: a person or entity that is registered with Yatuk to use the Services.') SSSS S SSSSSS SS SSSSSS SSSS SS SSSSSSSSSS SSSS SSSSS SS SSS SSS SSSSSSSSSXXXXX
                XXXXX
        XXXXXX
        XXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'What Information Do We Collect?') XXXXX
        XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We collect information from you when you visit our website, \n            register on our site, place an order, subscribe to our \n            newsletter, respond to a survey or fill out a form.\n            <ul>\n                <li>Name / Username</li>\n                <li>Phone Numbers</li>\n                <li>Email Addresses</li>\n                <li>Password</li>\n            </ul>\n            ') 
            SS SSSSSSS SSSSSSSSSSS SSSS SSS SSSS SSS SSSSS SSS SSSSSSSS 
            SSSSSSSS SS SSS SSSSS SSSSS SS SSSSSS SSSSSSSSS SS SSS 
            SSSSSSSSSSS SSSSSSS SS S SSSSSS SS SSSS SSS S SSSSS
            SSSS
                SSSSSSSS S SSSSSSSSSSSSS
                SSSSSSSSS SSSSSSSSSSSS
                SSSSSSSSS SSSSSSSSSSSSSS
                SSSSSSSSSSSSSSSSS
            SSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'How Do We Use The Information We Collect?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            <ul>\n                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>\n                <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>\n                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>\n                <li>To process transactions</li>\n                <li>To administer a contest, promotion, survey or other site feature</li>\n                <li>To send periodic emails</li>\n            </ul>\n            ') 
            SSSS
                SSSSSS SSSSSSSSSSS SSSS SSSSSSSSSS SSSSS SSSSSSSSSSS SSSSS SS SS SSSSSS SSSSSSS SS SSSS SSSSSSSSSS SSSSSSSSSSS
                SSSSSS SSSSSSS SSS SSSSSSS SSS SSSSSSSSSSS SSSSSS SS SSSSSSS SSS SSSSSSS SSSSSSSSS SSSSS SS SSS SSSSSSSSSSS SSS SSSSSSSS SS SSSSSSS SSSS SSSSSSSSS
                SSSSSS SSSSSSS SSSSSSSS SSSSSSS SSSSS SSSSSSSSSSS SSSSS SS SS SSSS SSSSSSSSSSS SSSSSSS SS SSSS SSSSSSSS SSSSSSS SSSSSSSS SSS SSSSSSS SSSSSSSSSSS
                SSSSSS SSSSSSS SSSSSSSSSSSSSSSSS
                SSSSSS SSSSSSSSSS S SSSSSSSS SSSSSSSSSS SSSSSS SS SSSSS SSSS SSSSSSSSSSSS
                SSSSSS SSSS SSSSSSSS SSSSSSSSSSS
            SSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'When does Yatuk use end user information from third parties?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Yatuk will collect End User Data necessary to provide the Yatuk services to our customers.\n            End users may voluntarily provide us with information they have made available on social\n             media websites. If you provide us with any such information, we may collect publicly available \n             information from the social media websites you have indicated. You can control how much of your \n             information social media websites make public by visiting these websites and changing your privacy settings.\n            ') 
            SSSSS SSSS SSSSSSS SSS SSSS SSSS SSSSSSSSS SS SSSSSSS SSS SSSSS SSSSSSSS SS SSS SSSSSSSSSS
            SSS SSSSS SSS SSSSSSSSSSS SSSSSSS SS SSSS SSSSSSSSSSS SSSS SSSS SSSS SSSSSSSSS SS SSSSSS
             SSSSS SSSSSSSSS SS SSS SSSSSSS SS SSSS SSS SSSS SSSSSSSSSSSS SS SSS SSSSSSS SSSSSSSS SSSSSSSSS 
             SSSSSSSSSSS SSSS SSS SSSSSS SSSSS SSSSSSSS SSS SSSS SSSSSSSSSS SSS SSS SSSSSSS SSS SSSS SS SSSS 
             SSSSSSSSSSS SSSSSS SSSSS SSSSSSSS SSSS SSSSSS SS SSSSSSSS SSSSS SSSSSSSS SSS SSSSSSSS SSSS SSSSSSS SSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'When does Yatuk use customer information from third parties?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We receive some information from the third parties when you contact us. For example, when you \n            submit your email address to us to show interest in becoming a Yatuk customer, we receive \n            information from a third party that provides automated fraud detection services to Yatuk. \n            We also occasionally collect information that is made publicly available on social media \n            websites. You can control how much of your information social media websites make public \n            by visiting these websites and changing your privacy settings.\n            ') 
            SS SSSSSSS SSSS SSSSSSSSSSS SSSS SSS SSSSS SSSSSSS SSSS SSS SSSSSSS SSS SSS SSSSSSSS SSSS SSS 
            SSSSSS SSSS SSSSS SSSSSSS SS SS SS SSSS SSSSSSSS SS SSSSSSSS S SSSSS SSSSSSSSS SS SSSSSSS 
            SSSSSSSSSSS SSSS S SSSSS SSSSS SSSS SSSSSSSS SSSSSSSSS SSSSS SSSSSSSSS SSSSSSSS SS SSSSSS 
            SS SSSS SSSSSSSSSSSS SSSSSSS SSSSSSSSSSS SSSS SS SSSS SSSSSSSS SSSSSSSSS SS SSSSSS SSSSS 
            SSSSSSSSS SSS SSS SSSSSSS SSS SSSS SS SSSS SSSSSSSSSSS SSSSSS SSSSS SSSSSSSS SSSS SSSSSS 
            SS SSSSSSSS SSSSS SSSSSSSS SSS SSSSSSSS SSSS SSSSSSS SSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Do we share the information we collect with third parties?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We may share the information that we collect, both personal and non-personal, with third \n            parties such as advertisers, contest sponsors, promotional and marketing partners, \n            and others who provide our content or whose products or services we think may interest you. \n            We may also share it with our current and future affiliated companies and business partners, \n            and if we are involved in a merger, asset sale or other business reorganization, we may also \n            share or transfer your personal and non-personal information to our successors-in-interest.\n\n            We may engage trusted third party service providers to perform functions and provide services \n            to us, such as hosting and maintaining our servers and the website, database storage and management, \n            e-mail management, storage marketing, credit card processing, customer service and fulfilling orders \n            for products and services you may purchase through the website. We will likely share your personal \n            information, and possibly some non-personal information, with these third parties to enable them to \n            perform these services for us and for you.\n            \n            We may share portions of our log file data, including IP addresses, for analytics purposes with \n            third parties such as web analytics partners, application developers, and ad networks. If your \n            IP address is shared, it may be used to estimate general location and other technographics such \n            as connection speed, whether you have visited the website in a shared location, and type of the \n            device used to visit the website. They may aggregate information about our advertising and what \n            you see on the website and then provide auditing, research and reporting for us and our advertisers. \n            We may also disclose personal and non-personal information about you to government or law enforcement \n            officials or private parties as we, in our sole discretion, believe necessary or appropriate in order \n            to respond to claims, legal process (including subpoenas), to protect our rights and interests or those \n            of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or \n            legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.\n            ') 
            SS SSS SSSSS SSS SSSSSSSSSSS SSSS SS SSSSSSSS SSSS SSSSSSSS SSS SSSSSSSSSSSSS SSSS SSSSS 
            SSSSSSS SSSS SS SSSSSSSSSSSS SSSSSSS SSSSSSSSS SSSSSSSSSSS SSS SSSSSSSSS SSSSSSSSS 
            SSS SSSSSS SSS SSSSSSS SSS SSSSSSS SS SSSSS SSSSSSSS SS SSSSSSSS SS SSSSS SSS SSSSSSSS SSSS 
            SS SSS SSSS SSSSS SS SSSS SSS SSSSSSS SSS SSSSSS SSSSSSSSSS SSSSSSSSS SSS SSSSSSSS SSSSSSSSS 
            SSS SS SS SSS SSSSSSSS SS S SSSSSSS SSSSS SSSS SS SSSSS SSSSSSSS SSSSSSSSSSSSSSS SS SSS SSSS 
            SSSSS SS SSSSSSSS SSSS SSSSSSSS SSS SSSSSSSSSSSS SSSSSSSSSSS SS SSS SSSSSSSSSSSSSSSSSSSSSSS

            SS SSS SSSSSS SSSSSSS SSSSS SSSSS SSSSSSS SSSSSSSSS SS SSSSSSS SSSSSSSSS SSS SSSSSSS SSSSSSSS 
            SS SSS SSSS SS SSSSSSS SSS SSSSSSSSSSS SSS SSSSSSS SSS SSS SSSSSSSS SSSSSSSS SSSSSSS SSS SSSSSSSSSSS 
            SSSSSS SSSSSSSSSSS SSSSSSS SSSSSSSSSS SSSSSS SSSS SSSSSSSSSSS SSSSSSSS SSSSSSS SSS SSSSSSSSSS SSSSSS 
            SSS SSSSSSSS SSS SSSSSSSS SSS SSS SSSSSSSS SSSSSSS SSS SSSSSSSS SS SSSS SSSSSS SSSSS SSSS SSSSSSSS 
            SSSSSSSSSSSS SSS SSSSSSSS SSSS SSSSSSSSSSSS SSSSSSSSSSSS SSSS SSSSS SSSSS SSSSSSS SS SSSSSS SSSS SS 
            SSSSSSS SSSSS SSSSSSSS SSS SS SSS SSS SSSS
            
            SS SSS SSSSS SSSSSSSS SS SSS SSS SSSS SSSSS SSSSSSSSS SS SSSSSSSSSS SSS SSSSSSSSS SSSSSSSS SSSS 
            SSSSS SSSSSSS SSSS SS SSS SSSSSSSSS SSSSSSSSS SSSSSSSSSSS SSSSSSSSSSS SSS SS SSSSSSSSS SS SSSS 
            SS SSSSSSS SS SSSSSSS SS SSS SS SSSS SS SSSSSSSS SSSSSSS SSSSSSSS SSS SSSSS SSSSSSSSSSSSSS SSSS 
            SS SSSSSSSSSS SSSSSS SSSSSSS SSS SSSS SSSSSSS SSS SSSSSSS SS S SSSSSS SSSSSSSSS SSS SSSS SS SSS 
            SSSSSS SSSS SS SSSSS SSS SSSSSSSS SSSS SSS SSSSSSSSS SSSSSSSSSSS SSSSS SSS SSSSSSSSSSS SSS SSSS 
            SSS SSS SS SSS SSSSSSS SSS SSSS SSSSSSS SSSSSSSSS SSSSSSSS SSS SSSSSSSSS SSS SS SSS SSS SSSSSSSSSSSS 
            SS SSS SSSS SSSSSSSS SSSSSSSS SSS SSSSSSSSSSSS SSSSSSSSSSS SSSSS SSS SS SSSSSSSSSS SS SSS SSSSSSSSSSS 
            SSSSSSSSS SS SSSSSSS SSSSSSS SS SSS SS SSS SSSS SSSSSSSSSSS SSSSSSS SSSSSSSSS SS SSSSSSSSSSS SS SSSSS 
            SS SSSSSSS SS SSSSSSS SSSSS SSSSSSS SSSSSSSSSS SSSSSSSSSSS SS SSSSSSS SSS SSSSSS SSS SSSSSSSSS SS SSSSS 
            SS S SSSSS SSSSSS SSS SSSSSS SS SSS SSSSSS SS SSS SSSSSSS SS SSSSSSS SS SSSS SSS SSSSSSSS SSSSSSSSSS SS 
            SSSSSSS SSSSSSSSSS SSSSSSSSS SS SS SSSSSSSSS SSSSSS SSSS SSSSSSSSSS SSSSS SSSSSSS SSSSS SSSSS SSS SSSSSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Where and when is information collected from customers and end users?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Yatuk will collect personal information that you submit to us. We may also receive personal \n            information about you from third parties as described above.\n            ') 
            SSSSS SSSS SSSSSSS SSSSSSSS SSSSSSSSSSS SSSS SSS SSSSSS SS SSS SS SSS SSSS SSSSSSS SSSSSSSS 
            SSSSSSSSSSS SSSSS SSS SSSS SSSSS SSSSSSS SS SSSSSSSSS SSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'How Do We Use Your Email Address?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            By submitting your email address on this website, you agree to receive emails from us. \n            You can cancel your participation in any of these email lists at any time by clicking on the \n            opt-out link or other unsubscribe option that is included in the respective email. \n            We only send emails to people who have authorized us to contact them, either directly, \n            or through a third party. We do not send unsolicited commercial emails, because we hate \n            spam as much as you do. By submitting your email address, you also agree to allow us to \n            use your email address for customer audience targeting on sites like Facebook, where we \n            display custom advertising to specific people who have opted-in to receive communications \n            from us. Email addresses submitted only through the order processing page will be used for \n            the sole purpose of sending you information and updates pertaining to your order. If, however, \n            you have provided the same email to us through another method, we may use it for any of the purposes \n            stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, \n            we include detailed unsubscribe instructions at the bottom of each email.\n            ') 
            SS SSSSSSSSSS SSSS SSSSS SSSSSSS SS SSSS SSSSSSSS SSS SSSSS SS SSSSSSS SSSSSS SSSS SSS 
            SSS SSS SSSSSS SSSS SSSSSSSSSSSSS SS SSS SS SSSSS SSSSS SSSSS SS SSS SSSS SS SSSSSSSS SS SSS 
            SSSSSSS SSSS SS SSSSS SSSSSSSSSSS SSSSSS SSSS SS SSSSSSSS SS SSS SSSSSSSSSS SSSSSS 
            SS SSSS SSSS SSSSSS SS SSSSSS SSS SSSS SSSSSSSSSS SS SS SSSSSSS SSSSS SSSSSS SSSSSSSSS 
            SS SSSSSSS S SSSSS SSSSSS SS SS SSS SSSS SSSSSSSSSSS SSSSSSSSSS SSSSSSS SSSSSSS SS SSSS 
            SSSS SS SSSS SS SSS SSS SS SSSSSSSSSS SSSS SSSSS SSSSSSSS SSS SSSS SSSSS SS SSSSS SS SS 
            SSS SSSS SSSSS SSSSSSS SSS SSSSSSSS SSSSSSSS SSSSSSSSS SS SSSSS SSSS SSSSSSSSS SSSSS SS 
            SSSSSSS SSSSSS SSSSSSSSSSS SS SSSSSSSS SSSSSS SSS SSSS SSSSSSSS SS SSSSSSS SSSSSSSSSSSSSS 
            SSSS SSS SSSSS SSSSSSSSS SSSSSSSSS SSSS SSSSSSS SSS SSSSS SSSSSSSSSS SSSS SSSS SS SSSS SSS 
            SSS SSSS SSSSSSS SS SSSSSSS SSS SSSSSSSSSSS SSS SSSSSSS SSSSSSSSSS SS SSSS SSSSSS SSS SSSSSSSS 
            SSS SSSS SSSSSSSS SSS SSSS SSSSS SS SS SSSSSSS SSSSSSS SSSSSSS SS SSS SSS SS SSS SSS SS SSS SSSSSSSS 
            SSSSSS SS SSSS SSSSSSS SSSSS SS SS SSS SSSS SSS SSSSS SSSS SS SSSSSSSSSSS SSSS SSSSSSSSS SSSSSS SSSSSSS 
            SS SSSSSSS SSSSSSSS SSSSSSSSSSS SSSSSSSSSSSS SS SSS SSSSSS SS SSSS SSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'How Long Do We Keep Your Information?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We keep your information only so long as we need it to provide Yatuk to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can’t identify you.\n            ') 
            SS SSSS SSSS SSSSSSSSSSS SSSS SS SSSS SS SS SSSS SS SS SSSSSSS SSSSS SS SSS SSS SSSSSSS SSS SSSSSSSS SSSSSSSSS SS SSSS SSSSSSS SSSS SS SSSS SSS SSSS SSS SSSSSS SSSS SS SSSSS SSSS SSSSSSSSSSS SSSS SSS SSS SSSSSSS SSS SSSSSSSS SS SSS SSSSSSS SSSS SS SS SSSSSS SSSS SS SSS SSSS SSSSSSSSSSS SSS SSSSS SS SS SSSS SSS SS SS SSSS SS SS SSSSSS SSSS SSS SSSSS SS SSSSSSSSSS SSSSSSSSSSSS SSSSS SSSSSS SSSSSS SS SSSS SSS SSSSSSS SS SSSSSSSSSSSSS SS SS SSSS SS SSSSS SSSSSSSS SSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'How Do We Protect Your Information?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Yatuk or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.\n            ') 
            SS SSSSSSSSS S SSSSSSS SS SSSSSSSS SSSSSSSS SS SSSSSSSS SSS SSSSSS SS SSSS SSSSSSSS SSSSSSSSSSS SSSS SSS SSSSS SS SSSSS SS SSSSSS SSSSSSS SS SSSSSS SSSS SSSSSSSS SSSSSSSSSSSS SS SSSSS SSS SSS SS S SSSSSS SSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSS SS SSSSSSSSSSS SSS SSSSSS SSSSSS SSSSS SSSSS SSSSSSSSSS SSS SSSS SSSSSSSSS SSSS SSS SSSSSSS SSSSSSS SSSSSSSSS SSSSSSSS SSSS SS SS SSSSSSSSSS SS SSSSS SSSSSSSSSS SSSS SSSSSSS SSSSSS SSSSSS SS SSSS SSSSSSSS SSS SSS SSSSSSSS SS SSSS SSS SSSSSSSSSSS SSSSSSSSSSSSS SSSSS S SSSSSSSSSSSS SSSS SSSSSSS SSSSSSSSSSS SSSSSSS SSSSSS SSSSSS SSSSSSSS SSSSSSSS SSSSSSSSSSS SSSSS SS SSSSS SSSS SS SSSSS SS SSSSSSS SSSSSSSS SSSSSS SS SSSSSSS SSS SSSSSSSS SSSSSSSS SS SSS SSSSSSSSSSS SSS SSSSSSSS SS SSSSS SS SSSSSSSSS SSSS SSSS SSSSSSSSSSS SS SSS SSSSSSS SSS SSS SS SSSSSSSSS SSSSSSSSSS SSSSSSSS SS SSSSSSSSS SS S SSSSSS SS SSS SS SSS SSSSSSSSS SSSSSSSSSS SS SSSSSSSSSS SSSSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Could my information be transferred to other countries?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Yatuk is incorporated in Armenia. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.\n            ') 
            SSSSS SS SSSSSSSSSSSS SS SSSSSSSS SSSSSSSSSSS SSSSSSSSS SSS SSS SSSSSSSS SSSSSSS SSSSSS SSSSSSSSSSSS SSSS SSSS SS SSSS SSS SS SSS SSSS SSSSSSSS SSS SS SSSSSSSSSSS SSSS SSSS SS SSSS SS SSS SSSSSSS SS SSSSSSSSSS SS SS SSSSS SSSSSSSS SSSSSSS SSSSSSSSSS SSS SSSSSS SSS SSS SS SSSSSS SSS SSSSSS SSSSSSSS SS SSS SSSSSS SSSSSSSSS SSSSSSSSS SSSS SSS SSS SSSS SSSS SS SSSSSSS SSSSSSSSSSSSS SSSSSSSSSS SSS SSS SSS SSSSSSSS SS SSSS SSSSS SS SSS SSSSSSS SSSSSS SSSSSSS SS SSSSSSSSSS SSSS SS SSSSS SSS SS SSS SSSSSS SSS SSSSSSSSSSS SSSSSSS SS SSS SSSSSSSSSSSS SSSSSSSS SSS SSSSSSS SS SSSS SSSSSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Is the information collected through the Yatuk Service secure?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.\n            ') 
            SS SSSS SSSSSSSSSSS SS SSSSSSS SSS SSSSSSSS SS SSSS SSSSSSSSSSSS SS SSSS SSSSSSSSS SSSSSSSSSSS SSS SSSSSSSSSS SSSSSSSSSS SS SSSS SSSSSSSSSS SSSSSSS SSSSSSSSSSSS SSSSSSS SSSSSSSS SSSS SSSSSSSSS SSS SSSSSSSSS SSS SSSS SSSSSSSSSSSS SSSSSSSS SSSSSSS SSSSSS SSS SSSSSSSS SSSSSSS SSS SSSSSSSSSS SSSSSSSSS SSSSSSSSSS SSSSSSSS SS SSSSSSSSS SSSSSS SSS SSSSSS SSSSSSSSSSS SSSSSSS SSSS SSSSSSSS SS SSSS SS SSSSSS SSSSSSSSS SSSSSSSSSS SSSSS SS SSS SSSSSSSSSS SSSSSSS SS SSSSSSS SSSS SSSSSSSS SSSSSSSSSSSS SS SSSSSS SSSSSSSSS SSS SSSSSSSS SSSSSSSSS SS SSSSSSSSSS SSS SSSSSSS SSS SSSSSSSSSSSSSSSS SSSS SS SSSSSSS SSSS SSSSSSSS SSSSSSSSSSSS SSS SSSSS SSSS SSSSSSSSSSS SSSSSSSSSS SSSS SS SSS SSSSSSSSS SSSS SS SSSSSSS SSS SSSSSSSSSS SSSS SSSS SSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Can I update or correct my information?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            The rights you have to request updates or corrections to the information Yatuk collects depend on your relationship with Yatuk. Personnel may update or correct their information as detailed in our internal company employment policies.\n\n            Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.\n            \n            You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.\n            \n            If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.\n            ') 
            SSS SSSSSS SSS SSSS SS SSSSSSS SSSSSSS SS SSSSSSSSSSS SS SSS SSSSSSSSSSS SSSSS SSSSSSSS SSSSSS SS SSSS SSSSSSSSSSSS SSSS SSSSSS SSSSSSSSS SSS SSSSSS SS SSSSSSS SSSSS SSSSSSSSSSS SS SSSSSSSS SS SSS SSSSSSSS SSSSSSS SSSSSSSSSS SSSSSSSSS

            SSSSSSSSS SSSS SSS SSSSS SS SSSSSSS SSS SSSSSSSSSSS SS SSSSSSS SSSS SSS SSSSSSSSSSS SS SSSSSSSSSS SSSSSSSSSSSS SSSSSSSSSSS SS SSSSSSSS SSS SSS SSSSSSS SS SS SSSSS SS SSS SSSSSS SS SSSSSSS SSSS SSSSSSSSSS SSSSSSSSSSSS SSSSSSSSSSSS SSS SSSSSS SSSS SSSSSSSSSSS SSSS SSSSSSS SS SSSSSSSSSSSSSS SSS SSSSS SSSSSSSSSSS SSS SSSSSSS SSSS SSS SS SSS SSSSSS SSS SSSSSSSSSS SSSSSSSSSSSS SSSSSSSSSSS SSSSSSSSSS SSSSS SSS SS SSS SSSSSSS SSSSSSSS SS SSS SSSSSSSSS SSSSSSSSSSS SS SSSSSSSSSS SSSS SSSSSSSS SSSS SSSSSSSS SSSSSSSSSSSS SSSSSSS SSS SSSSSSSSS SSSS SSSS SS SSSSSS SS SSSSS SSSSSSSSSSS SSSS SS SSSSSSSSS SS SSSSSSSSSSS SSSS SS SSSS SSSSSSSS SS SSSSS SSSSSSS SS SSSSSSSSSS SSSS SSSS SSSSSSS SSSSSS SSSSS SS SSSS SSSSSSS SSSSSSSSSSS SSSSSS SS SSSSSSSSS SS SSSSSSS SSSS SSSSSSS SSS SSSSSSSSS SS SSS SSSS SSSSSSSSSS SSSSS SSSSS SS SSSSSSSSSS S SSSSSS SSSSSSSSS SS SSSSSS SSSS SSSSSSSS SSSSSS SSSSSSSS SSS SSSSSSS SSSSSS SS SSSSSS SSSSSSSSSSSS SSS SSS SSSSSSSSSSS SSS SSSSSSSSSSS SSS SSSSSSS SS SSSS SSSSSS SSSSSSSS SSS SSSSSSS SSSSSSSSSSS SS SSS SSSSSS
            
            SSS SSSSSS SS SSSSS SSSS SS SS SSS SSSSSSSSSSSSSSS SSSSSSSS SS SSSSSS SSSS SSS SSSSS SSSSSS SS SSS SSSSSSSSSSS SSS SSSS SSSSSSSS SS SS SSSS SSS SSSSSSS SSS SSSS SS SSSS SS SSS SSSSSSS SS SSSSSSS SSSSSSSSSSS SSSS SSSSSSSSSSS SSSS SSSSS SSSS S SSSS SS SSSS SSSSSSSSSSS SSS SSSSS SS S SSSSSSSSSSSS SSSS SSSS SSSS SS SSSSSSSSS SS SSSSSSSSSS SSS SS SS SSSSSSS SSSSSSSS SSSSS SSSSSSSSS SSSS SSSSSSSS SSS SSSSSSSS SSSSSSSSSSS SSSSSS SS SSSSSSSSS SS SSSSSSSS SSSS SSS SSSSS SSSSSSS SSSSSSSSSS SSSSS SSSS SS SSSSSSSS SSSSSSSSSS SSSSSSS SS SSSSSSSS SS SSSSSSSSSSSS SS SSSS SS SSS SS SSS SSSSSS SSSSSSSSSS SSS SSSSSSSSSSS SSSSSSSSSSSS
            
            SS SSS SSS SS SSS SSSS SSS SSSS SS SSSSSSS SSSSSSS SS SSSSSSS SSS SSSSSSSSSSS SS SSSS SSSSS SSSS SSS SSS SS SS SS SSSSSSSSSS SSS SSSSSSSSSSSS SS SSSSS SSS SSS S SSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Personnel') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            If you are a Yatuk worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.\n\n            You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.\n            ') 
            SS SSS SSS S SSSSS SSSSSS SS SSSSSSSSSS SS SSSSSSS SSSSSSSSSSS SSS SSSSSSSSSSS SSSSSSS SS SSS SS SSS SSS SSSSSSSSSSS SSSSSSSSS SSS SSSSS SSSSSSSSS SSSSSSSS SS SSSSS SS SSSSSSSSSS SSSSSSSS SS SSSSSSS SSS SSSSSS SSSSSSSSSSS

            SSS SSS SSSSSSS SS SS SSSSS SS SSS SSSSSS SS SSSSSSS SSSS SSSSSSSSSSSS SSS SSSSSS SSSS SSSSSSSSSSS SSSS SSSSSSS SS SSSSSSSSSSSSSS SSS SSSSS SSSSSSSSSSS SSS SSSSSSS SSSS SSS SS SSS SSSSSSS S SSSSSS SS SSS SSSSSSSSSSS SS SSSS SSSSSSSS SS SSSS SSSS SSSSSSSS SSSSSSSSSSSS SSSSSSS SSS SSSSSSSSS SSSS SSSS SS SSSSSS SS SSSSS SSSSSSSSSSS SSSS SS SSSSSSSSS SS SSSSSSSSSSS SSSS SS SSSS SSSSSSSS SS SSSSS SSSSSSS SS SSSSSSSSSS SSSS SSSS SSSSSSS SSSSSS SSSSS SS SSSS SSSSSSS SSSSSSSSSSS SSSSSS SS SSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Sale of Business') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Yatuk or any of its Corporate Affiliates (as defined herein), or that portion of Yatuk or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.\n            ') 
            SS SSSSSSS SSS SSSSS SS SSSSSSSS SSSSSSSSSSS SS S SSSSS SSSSS SS SSS SSSSS SS S SSSSS SSSSSS SS SSSSS SSSSSSSS SS SSS SS SSSSSSSSSSSSS SSS SS SSS SSSSSS SS SSSSS SS SSS SS SSS SSSSSSSSS SSSSSSSSSS SSS SSSSSSS SSSSSSSS SS SSSS SSSSSSS SS SSSSS SS SSS SS SSS SSSSSSSSS SSSSSSSSSS SS SSSSS SSS SSSSSSS SSSSSSSS SS SS SSS SSSSS SSSS SS SSSSSSSSSSS SSS SSSSSSSS SS SSSS S SSSSSSSS SS SSSS SSSSS SSSSSSS SS S SSSSSSSS SS SSSSSSSSSSS SSSSSSSSSSSSSS SS SSSSSSS SSSSSSSSSSS SSSSSSSS SSSS SSS SSSSS SSSSS SSSSSS SS SSSSSS SS SSS SSSSS SS SSSS SSSSSSS SSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Affiliates') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity which directly or indirectly controls, is controlled by or is under common control with Yatuk, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.\n            ') 
            SS SSS SSSSSSSS SSSSSSSSSSS SSSSSSSSSS SSSSSSSS SSSSSSSSSSSS SSSSS SSS SS SSS SSSSSSSSS SSSSSSSSSSS SSS SSSSSSSS SS SSSS SSSSSSS SSSSSSS SSSSSSSSSS SSSSSSSSSS SSSSS SSS SSSSSS SS SSSSSS SSSSS SSSSSSSS SS SSSSSSSSSS SSSSSSSSS SS SSSSSSSSSS SS SS SS SSSSS SSSSSS SSSSSSS SSSS SSSSSS SSSSSSS SS SSSSSSSSS SS SSSSSSSSSS SSS SSSSSSSSSSS SSSSSSSS SS SSS SSSS SS SSSSSSS SS SSS SSSSSSSSS SSSSSSSSSS SSSS SS SSSSSSS SS SSSSS SSSSSSSSS SSSSSSSSSS SS SSSSSSSSSS SSSS SSS SSSSS SS SSSS SSSSSSS SSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Governing Law') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            This Privacy Policy is governed by the laws of Armenia without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.\n\n            The laws of Armenia, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.\n            \n            By using Yatuk or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.\n            ') 
            SSSS SSSSSSS SSSSSS SS SSSSSSSS SS SSS SSSS SS SSSSSSS SSSSSSS SSSSSS SS SSS SSSSSSSS SS SSSS SSSSSSSSSS SSS SSSSSSS SS SSS SSSSSSSSS SSSSSSSSSSSS SS SSS SSSSSS SS SSSSSSSSSS SSSS SSS SSSSSS SS SSSSSSS SSSSSSS SSSSSSS SSS SSSSSSS SSSSS SS SS SSSSSSSSSS SSSS SSSS SSSSSSS SSSSSS SSSSSS SSS SSSSS SSSSSSSSSSS SSS SSS SSSS SSSSSS SS SSSS SSSSSS SSSSS SSSSSSS SSSSSSS SS SSS SSSSSSSS SSSSSSSSSS

            SSS SSSS SS SSSSSSSS SSSSSSSSS SSS SSSSSSSSS SS SSS SSSSSS SSSSS SSSSSS SSSS SSSSSSSSS SSS SSSS SSS SS SSS SSSSSSSS SSSS SSS SS SSS SSSSSSS SSS SSSS SS SSSSSSS SS SSSSS SSSSSS SSSSSS SSSSSSSSS SS SSSSSSSSSSSSS SSSSS
            
            SS SSSSS SSSSS SS SSSSSSSSSS SS SSSSSSSSS SSS SSSSSSS SSSS SSSSSSSSSS SS SSSS SSSSSSS SSSSSSS SS SSS SS SSS SSSSS SS SSSS SSSSSSS SSSSSSS SSS SSSSSS SSS SSSSSS SSSS SSS SSSSSSSS SS SSS SSS SSSSSSSSS SSSSSSSSS SSS SS SSS SSSSSSSS SSSSSS SSSSSSSSSS SSSS SSS SS SSSSSSSSS SSS SSSSSSS SS SSSSSSS SS SSSS SSSSSSS SSSSSS SSSS SS SSS SSSSSSSSSSSSS SSSSSS SSS SSS SS SSSSSSSSSS SS SSSS SSSSSSSS SSSSSSSSSSS SSSS SSSS SSSS SSS SSSSSS SSSSS SSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Your Consent') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We’ve updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it’s being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.\n            ') 
            SSSSS SSSSSSS SSS SSSSSSS SSSSSS SS SSSSSSS SSS SSSS SSSSSSSS SSSSSSSSSSSS SSSS SSSS SS SSSSS SSS SSSS SSS SSSSS SSS SSSS SSS SSS SSSS SSSSS SSSSS SS SSSSS SSS SSSSSSSS SSSSSSSSSSS SS SSSSSSSS SS SSSSSS S SSSSSSSSS SSS SSSSSS SSSSSSS SS SSS SSSSSSS SSSSSS SSS SSSSS SS SSS SSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Links to Other Websites') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Yatuk. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.\n            ') 
            SSSS SSSSSSS SSSSSS SSSSSSS SSSS SS SSS SSSSSSSSS SSS SSSSSSSS SSS SSSSSSS SSSSS SS SSSSS SSSSSSSS SSS SSSSSSSS SS SSSSSSSSSS SS SSSSSS SS SSS SSS SSSSSSSSSSS SSS SSS SSSSSSSS SSSSSSSS SS SSSSSSSS SSSSSSSSS SS SSSS SSSSSSSSS SSS SSSS SSSSSSSS SSS SSS SSSSSSSSSSSSS SSSSSSSSS SS SSSSSSS SSS SSSSSSSS SS SSSSSSSSSSSS SS SSS SSSSSS SSSSSSSS SSSS SSSS SSS SSS S SSSS SS SS SSSS SSS SSSSSSSS SS SSSSSSS SSSSSSSS SSS SSSSSSS SSSSSS SS SS SSSSSS SS SSSSSSS SSSS SSSSSSSS SSS SSSSSSSSSSS SS SSS SSSSS SSSSSSSS SSSSSSSSS SSSSS SSSS SSSS S SSSS SS SSS SSSSSSSSS SS SSSSSSS SS SSSS SSSSSSSSS SSS SSSSS SSS SSSSSSSSS SSSS SSSSS SSSSSSS SSS SSS SSSSS SSS SSSSSSS SS SSSSS SSSSSSS SS SSSSSSS SSSSSSSSSSS SSSSS SSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Cookies') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Yatuk uses “Cookies” to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.\n            ') 
            SSSSS SSSS SSSSSSSSS SS SSSSSSSS SSS SSSSS SS SSS SSSSSSS SSSS SSS SSSS SSSSSSSS S SSSSSS SS S SSSSS SSSSS SS SSSS SSSSSS SS SSSS SSSSSSSS SS SSSSSS SSSSSS SS SSSS SSS SSSSSSSS SS SSS SSSSSSS SS SSSSSSS SSS SSSSSSSSSSS SSS SSSSSSSSSSSSS SS SSS SSSSSSS SSS SSS SSSSSSSSSSSSS SS SSSSS SSSS SSSSSSSS SSSSSSS SSSSS SSSSSSSS SSSSSSS SSSSSSSSSSSSS SSSS SSSSSS SSS SSSSSS SSSSSSSSSSS SS SSS SSSSS SS SSSSSSSS SS SSSSS SSSS SSSSS SSSSSSS SSSSS SSSS SSS SSSSS SSS SSSSSSS SS SS SSSSS SSS SS SSSS SS SSSSSSSS SSSS SSS SSS SSSSSS SS SSSSSSSSSSS SSSS SSS SSSSSSSS SSS SS SSS SS SSSSSSS SSS SSS SS SSSSSSSS SSSSSSSS SS SSS SSSSSSS SSSSSSSS SSS SSS SSS SS SSSS SS SSSSSS SSSSSSSSSSSSS SS SSS SSSSSSS SSSSSSSSS SS SS SSSS SS SSSSS SSSSS SSSSSSSSSS SSSSSSSSSSSS SSSSSSSSSSS SS SSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Blocking and disabling cookies and similar technologies') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Wherever you’re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser’s help menu for more information.\n            ') 
            SSSSSSSS SSSSSS SSSSSSS SSS SSS SSSS SSS SSSS SSSSSSS SS SSSSS SSSSSSS SSS SSSSSSS SSSSSSSSSSSSS SSS SSSS SSSSSS SSS SSSSS SSS SSSSSSSSS SSSSSSS SSS SSSSSSS SSS SSSSSSS SSSS SSSSSSSSSSS SSSSSSSSS SSS SSS SSS SSS SS SSSS SS SSSSS SSSSSSS SSS SS SSS SSSSSSSS SSS SSSSSSSSS SSS SSSSSS SSSS SS SSSSS SSSS SSS SSS SSSS SSSS SSSS SSSSS SSSSSSSSSSS SSSSS SSSSS SSSSS SSSSSSSS SSSS SSSSSSSSSSSS SS SSS SSSSS SSSSSSS SS SSSS SSSSSSSS SSSSSSSSS SSSSSSSS SSSS SSSSSSSSS SSSSSSSS SSSSSSSSS SS SSSS SSSSSSSSS S SSSSSS SS SSSSSSSS SS SSSSSS SSSS SSS SSSSSS SSS SSSSSS SSSS SSSS SSSSSSSS SSS SSSS SSSS SS SS SSSS SSSSSSSS SSSS SSSSSS SSSS SSSSSSSS SSS SSSSSS SSSSS SSSS SSSSSSSSS SSSS SSSS SSS SSSS SSSSSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Payment Details') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.\n            ') 
            SS SSSSSSS SS SSS SSSSSS SSSS SS SSSSS SSSSSSS SSSSSSSSSS SSSSSSS SSS SSSS SSSSSSSS SSS SS SSSSSS SSSS SSSS SSSSSSSSSSSS SSSSSSSSSSS SSSS SS SSSSSS SS SSS SSSS SSSSSS SSSSSS SSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Kids’ Privacy') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.\n\n            ') 
            SS SSSSSSS SSSSSSSSSSS SSSS SSSS SSSSS SSS SSS SS SS SSSS SS SSSSSS SSS SSSSSSSSS SS SSS SSS S SSSSSS SS SSSSSSSS SSS SSS SSS SSSSS SSSS SSSS SSSSS SSS SSSSSSSS SS SSSS SSSSSSSS SSSS SSSSSSS SSSS SSSSSSSSSSS SSSSSS SSSSSSS SSS SS SS SSSSSS SSSSS SSSS SS SSSS SSSSSSSSS SSSSSSSS SSSS SSSS SSSSSS SSSSS SSS SSS SS SS SSSSSSS SSSSSSSSSSSS SS SSSSSSSS SSSSSSSS SS SSSS SSSSS SS SSSSSS SSSS SSSSSSSSSSS SSSS SSS SSSSSSSS

            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Changes To Our Privacy Policy') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.\n            ') 
            SS SSS SSSSSS SSS SSSSSSS SSS SSSSSSSSS SSS SS SSS SSSS SS SSSS SSSSSSS SS SSSS SSSSSSS SSSSSS SS SSSS SSSS SSSSSSSSSS SSSSSSS SSS SSSSSSS SSS SSSSSSSSS SSSSSS SSSSSSSSS SSSSSSSS SS SSSS SS SSSS SSSSSS SSS SSSS SSSSSSSS SSSSSSS SSS SSSSSSSS SSSSSS SS SSSS SSSSSSS SS SSSS SSSSSSS SSSSSS SSS SSSS SSS SS SSSSSSSSSSS SS SSSSSS SSSS SSSSSS SSSS SS SSSS SSSSSSS SSSSS SS SSS SSSSSSSS SS SSS SSS SSSSSSSS SSS SSSS SS SSSSS SS SSS SSSSSSS SSSSSSS SSSSSSS SS SSS SS SSS SSSS SS SSSSS SS SSSS SS SSS SSSSSSS SSSSSSS SSSSSSS SSS SSS SSSSSS SSSS SSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Third-Party Services') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third- Party Services”).\n\n            You acknowledge and agree that Yatuk shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Yatuk does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.\n            \n            Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties’ terms and conditions.\n            ') 
            SS SSS SSSSSSSS SSSSSSS SS SSSS SSSSSSSSS SSSSSSSSSSS SSSSSSS SSSSSSSSSS SSSSS SSSSSSSSSSSS SSSSSSSSSSSS SSS SSSSS SSSSSSSS SSSSSSSSS SS SSSSSSS SSSSS SS SSSSSSSSSSS SSSSSSSS SS SSSSSSSS SSSSSSSS SSSSS SSSSSSSSSSS

            SSS SSSSSSSSSSS SSS SSSSS SSSS SSSSS SSSSS SSS SS SSSSSSSSSSS SSS SSS SSSSSSSSSSS SSSSSSSSS SSSSSSSSS SSSSS SSSSSSSSS SSSSSSSSSSSSS SSSSSSSSSSS SSSSSSSSS SSSSSSSSS SSSSSSSSSSS SSSSSSSSS SSSSSSSS SSSSSSS SS SSS SSSSS SSSSSS SSSSSSSS SSSSS SSSS SSS SSSSSS SSS SSSSS SSS SSSS SSS SSSSSSSSS SS SSSSSSSSSSSSSS SS SSS SS SSS SSSSS SSSSSS SS SSSSSS SSS SSS SSSSSSSSSSS SSSSSSSSS
            
            SSSSSSSSSSS SSSSSSSS SSS SSSSS SSSSSSS SSS SSSSSSSS SSSSSS SS S SSSSSSSSSSS SS SSS SSS SSS SSSSSS SSS SSS SSSS SSSSSSSS SS SSSS SSS SSSS SSS SSSSSSS SS SSSS SSSSS SSSSSSSS SSSSS SSS SSSSSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Tracking Technologies') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Cookies\n            We use Cookies to enhance the performance and functionality of our $platform but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the $platform as we would not be able to remember that you had logged in previously.\n            \n            Local Storage\n            Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.\n            \n            Sessions\n            $elnombre uses “Sessions” to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.\n            ') 
            SSSSSSS
            SS SSS SSSSSSS SS SSSSSSS SSS SSSSSSSSSSS SSS SSSSSSSSSSSSS SS SSS SSSSSSSSS SSS SSS SSSSSSSSSSSSS SS SSSSS SSSS SSSSSSSS SSSSSSS SSSSS SSSSSSSS SSSSSSS SSSSSSSSSSSSS SSSS SSSSSS SSS SSSSSS SSSSSSSSSSS SS SSS SSSSS SS SSSSSSSS SS SSSSS SSSS SSSSS SSSSSSS SSSSS SSSS SSS SSSSS SSS SSSSSSSSS SS SS SSSSS SSS SS SSSS SS SSSSSSSS SSSS SSS SSS SSSSSS SS SSSSSSSSSSS
            
            SSSSS SSSSSSS
            SSSSS SSSSSSS SSSSSSSSS SSSSS SS SSS SSSSSSSS SSSSSSSS SSS SSSS SSSS SSSSSSS SSS SSSSSSSSS SSS SSSSSSS SSSSSSSSSSS SSSSS SSS SSSSSSS SSSSSSSS SSSSSSSSSS SSSS SSSSSSSS SSSSSSS SS SSSSSSS SSS SSSS S SSSSSSS SSSSSSSS SSSSSSSS SSS SS SSSSSSSSSSS SSSSSS SS SSS SSSS SSSSSSS SSSSSSS
            
            SSSSSSSS
            SSSSSSSSS SSSS SSSSSSSSSS SS SSSSSSSS SSS SSSSS SS SSS SSSSSSS SSSS SSS SSSS SSSSSSSS S SSSSSSS SS S SSSSS SSSSS SS SSSS SSSSSS SS SSSS SSSSSSSS SS SSSSSS SSSSSS SS SSSS SSS SSSSSSSS
            
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX gettext(u'Contact Us') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
             gettext(u'\n            Don’t hesitate to contact us if you have any questions.\n\n            Via Email: stepankakosyan22@gmail.com\n            Via Phone Number: +37495011553\n            ') 
            SSSSS SSSSSSSS SS SSSSSSS SS SS SSS SSSS SSS SSSSSSSSSS

            SSS SSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS
            SSS SSSSS SSSSSSS SSSSSSSSSSSS
            
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB