BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XX XXXXXXXXX XXXXXXXXXX
XXXXXXXXXXXX X  gettext(u'Shipping') XXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX gettext(u'Shipping Methods') XXXXX
        XXXXXX gettext(u'Whichever option you will choose product will be delivered without any problem') XXXXXXX
    XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX
                
            XXXX
        XXXXXX
    BBBBBB

XXXXXX
XXXXXX
BBBBBBBB BBBBBBB