BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XX XXXXXXXX XXXXXX X XXXX XXXXXXXX XXXXXXXXXXXX
XXXXXXX gettext(u'Yatuk')  X  gettext(u'Store') XXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XX XXXXXXXX XXXXXX X XXXX XXXXXXXX XXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

BBBBBBBB
BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBB