
BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB

BBBBB BBBBB gettext(u'Costs') BBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB