BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBB gettext(u'Transfers')  BBBBBBBB
X
BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Transfers') XXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXBBB BBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Transfer') XXXXXXXXX
      XXXXXX
      XXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Filters')  XX
            XXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXX

      XXXX
      XXXX XXXXXXXXXXXXXXX BB BBBB BB BBBBB BB BBBB BB BBBBBXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Product') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXX BB BBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
              BBB BBBBBBB BB BBBBBBBB
              XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
              BBBBBB
            XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Collaborator') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXX BB BBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
              BBB BBBBB BB BBBBBBBBBBBBB
              XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
              BBBBBB
            XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB