
BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBB  gettext(u'Sellings') BBBBBBBB
X
BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX gettext(u'Sellings') XXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXXXBBB BBBBBBBBBBBBBBBBB
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X gettext(u'New Sell') XXXXXXXXX
        XXXXXX
        XXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Filters')  XX
              XXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXX
        XXXX XXXXXXXXXXXXXXX BB BBBB BB BBBBB BB BBBB BB BBBBB  BB BBBB BB BBBBBXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Product') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX BB BBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                BBBBBB
              XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Type') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX BB BBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
                BBB BB BB BBBBB
                XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                BBBBBB
              XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Collaborator') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX BB BBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All') XXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBB
                XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                BBBBBB
              XXXXXXXXX
            XXXXXX

          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB