BBBB BBBB
XXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        BBBBBB
    XXXXXX
XXXXXX
