BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
        BB BBBB
            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Address') XXXXXX
                BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXX gettext(u'Choose from your addresses') XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXXBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Shipping method') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXBBB BBBBBBBBBBBBBBBX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                         
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXX gettext(u'I have read and agree to the website')  XXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX gettext(u'terms and conditions') 
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                    XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX
                    
                XXXXXX
                    XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXBBB BBBBBBBBBBX
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX gettext(u'Make Payment') XXXXXXXXX
                XXXXXX
            XXXXXX

            XXXXXXX
            
        BBBBB
        BB BBBBBBBB
            XXX XXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXXXXXX
                BBBBBB
            XXXXX
        BBBBB

    XXXXXX
XXXXXX
