BBBB BBBBBBBBBB
BBBB BBBB
BB BBBBBBBBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX gettext(u'Name') XXXXX
      XXXX gettext(u'Circulation') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
    XXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXXXBB BBBBBBBBBBBBBBBBFFFFFFFFFFFF BBBB X BBBBBXXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX
BBBB
 gettext(u'No Collaborators yet') 
BBBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        X XXXX BBBBB BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XX XXXXXXXXXXXXX
          XXXXXXXXXX  BB BBBB BB BBB XXXXXXXX XXXXXX BBBBXXXXXXXXXXXXXXXXBBBBBX
          XXXXXXXXBBB BBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          
      XXXX
      BBBBBB
  
      BB BBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
  
    XXXXXX
  XXXXXX