BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        
    BB BBBBBBBB
        XXX XXXXXXXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
            XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXXXXXX
            BBBBBB
        XXXXX
    BBBBB
BB BBBB
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            BBB BBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                    
                    
                    BB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            BBBBBB
            XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXBBB BBBBBBBBBBBBX
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX gettext(u'Send') XXXXXXXXX
        XXXXXXX
        BBBBB
    XXXXXX
XXXXXX
