BBBB BBBBBBBBBB
BBBB BBBB
BB BBBBBBBBBBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX gettext(u'Name') XXXXX
      XXXX gettext(u'Contact Info') XXXXX
      XXXX gettext(u'Text') XXXXX
      XXXX gettext(u'Is Seen') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBBBBBBBB BB BBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBB
  XXXXXXXX
XXXXXXXX
BBBB
 gettext(u'No Contact Messages yet') 
BBBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        X XXXX BBBBB BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XX XXXXXXXXXXXXX
          XXXXXXXXXX  BB BBBB BB BBB XXXXXXXX XXXXXX BBBBXXXXXXXXXXXXXXXXBBBBBX
          XXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          
      XXXX
      BBBBBB
  
      BB BBBBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
  
    XXXXXX
  XXXXXX