BBBB BBBB
XXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX
      
    XXXXX
    XXXX
      
    XXXXX
    XXXX
      
    XXXXX
    XXXX
        BB BBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX
        BBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            X gettext(u'Checked') 
            XXXXXXXXX
        BBBBB
    XXXXX
XXXXX