BBBB BBBBBBBBBB
BBBB BBBB
BB BBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX XXXXX
      XXXX gettext(u'Product') XXXXX
      XXXX gettext(u'Price') XXXXX
      XXXX gettext(u'Type') XXXXX
      XXXX gettext(u'Note') XXXXX
      XXXX gettext(u'Date') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBB BB BBBBB
    XXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXFFFFFFFFFFFXXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      X XXXX BBBBB BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB XX XXXXXXXXXXXXX
        XXXXXXXXXX  BB BBBB BB BBB XXXXXXXX XXXXXX BBBBXXXXXXXXXXXXXXXXBBBBBX
        XXXXXXXXBBB BBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        
    XXXX
    BBBBBB

    BB BBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB

  XXXXXX
XXXXXX
BBBB
 gettext(u'No Costs yet') 
BBBBB