BBBB BBBB

BBB BBBB BB  BBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX X 
         XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXXX gettext(u'Play Online') XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBB
