BBBB BBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BB BBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXXXXXXXX
      XXXX gettext(u'User') XXXXX
      XXXX gettext(u'Products') XXXXX
      XXXX gettext(u'Shipping Method') XXXXX
      XXXX gettext(u'Comment') XXXXX
      XXXX gettext(u'Amount') XXXXX
      XXXX gettext(u'Status') XXXXX
      XXXX gettext(u'Date') XXXXX
      XXXXXXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBBB BB BBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBB
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      X XXXX BBBBB BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB XX XXXXXXXXXXXXX
        XXXXXXXXXX  BB BBBB BB BBB XXXXXXXX XXXXXX BBBBXXXXXXXXXXXXXXXXBBBBBX
        XXXXXXXXBBB BBBBBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        
    XXXX
    BBBBBB

    BB BBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
  XXXXXX
XXXXXX
BBBB
 gettext(u'No Orders yet') 
BBBBB
