BBBB BBBBBB
BBBB BBBBBBBBBB
BBBB BBBB
XXX XXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
XXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX 
    XXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXXXXXXXX
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBB BBBBBBBBBB BB BBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXX X  X XXXXXXXXXXXXX
      BBBBBB
    XXXXXX
  XXXXX
  XXXX
    XXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB XXXXXX
    XXXXXX
    XXXXX
    XXXXXXXXX
  XXXXXXXXXX
  XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXFFFFFFFFFFFXXXXX
  XXXX
    BB BBBBBBBBBBBB BB BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'In Process') XXXXXXXXX
    BBBB BBBBBBBBBBBB BB BBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Shipping') XXXXXXXXX
    BBBB BBBBBBBBBBBB BB BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Done') XXXXXXXXX
    BBBBB
  XXXXX
XXXXX