BBBB BBBB
XXXX XXXXXXXXXXXXXX
  BB BBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBXXXXXXXBBBBB
        XXXXXXXXBBB BBBBBBBX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXX
      XX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'All') XXXXXXXX
      XXXXXX
  XXXXXX
  BBB BBBBBBBB BB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXXBBBBB
        XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXX
      XX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXX
        XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  BBBBBB
XXXXXX
BBBBB
XXXXXX
BBB BBBBBBB BB  BBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XX  XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sold out') XXXXXXBBBBB
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXXXX gettext(u'Price') XXXXXXX
          XXXXXXXXXXXXXX
        XXXXXX
      XXXX
      BB BBB BBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Add to card') 
          XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBB
