BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Store') XXXXX
        XXXXX
      XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
XXXXXX
