XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    BBB BBBBBB BB BBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBX
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBBBXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    BBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBB
  XXXXXX
  