BBBB BBBB
XXXX  XXXXXXXXBBB BBBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX 
    XXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX X XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
                                XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                            XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX
                                XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXX
                                XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                            XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
                            XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXX
                            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Total') XXXXXXX XXXXXX  gettext(u'֏') XXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Checkout') XXXXXXXXXXXXX
XXXXXX
BBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXX XXXXXX  XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX gettext(u"Don't say you didn't like anything. Go back and choose something.") XXXXXX
    XXXXX
BBBBB
XXXXXX
