BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX gettext(u'To Do List') XXXXX
      XXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXX
        BBBBBBBBBB
        FFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF
        XXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
        X gettext(u'Add New') XXXXXXXXX
      XXXXXX
    XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX

        XXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBB BB BB BBBBB
          XXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBXXXXXXXBBBBB
                  XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
                  
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXXXFFFFFFFFFFF FFFFXXXXXX
            XXXXXX
            XXXXXX
            XX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          BBBBB
           gettext(u'To Do List is empty') 
            BBBBBB
      XXXXX
      XXXXXX
    XXXXXX
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
      XXXXXXBBB BBBBBBBX
    X gettext(u'Show All') XXXX
  XXXXXX