BBBB BBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX gettext(u'To Do List') XXXXX

  XXXXXX
  XXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXX
      BBBBBBBBBB
      FFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF
      XXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXBBB BBBBBBBBBBX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
      X gettext(u'Add New') XXXXXXXXX
    XXXXXX
  XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBB
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
        XXXX
          XXXX gettext(u'Done') XXXXX
          XXXX gettext(u'Text') XXXXX
          XXXX gettext(u'Date') XXXXX
          XXXXXXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBB BB BBBBB
XXXX
  XXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBXXXXXXXBBBBB
                      XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBX
                      XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX  
                  XX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
          XXXXXX
      XXXXXX
  XXXXX
  XXXXXXXXX
  XXXXFFFFFFFFFFFXXXXX
  XXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX 
          XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBX
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
  XXXXX
XXXXX
BBBBBB
        
      XXXXXXXX
    XXXXXXXX
    BBBB
     gettext(u'To Do List is empty') 
    BBBBB
  XXXXXX