BBBB BBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX gettext(u'Products - ') XXXXXXX XXXXXX  gettext(u'֏') XXXXXXXXXXXXX
    XXXXXXXXXXX gettext(u'Shipping - ') XXXXXXX XXXXXX  gettext(u'֏') XXXXXXXXXXXXX
    BB BBBBBBBBBBBBBB
    XXXXXXXXXXX gettext(u'Total - ') XXXXXXX XXXXXXFFFFFFFFFFFFFFFFFF  gettext(u'֏') XXXXXXXXXXXXX
    BBBB
    XXXXXXXXXXX gettext(u'Total - ') XXXXXXX XXXXXX  gettext(u'֏') XXXXXXXXXXXXX

    BBBBB
XXXXXX
