BBBB BBBBBBBBBB
BBBB BBBB
BB BBBBBBBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX gettext(u'Image') XXXXX
      XXXX gettext(u'Product') XXXXX
      XXXX gettext(u'Count') XXXXX
      XXXX gettext(u'Price') XXXXX
      XXXX gettext(u'Type') XXXXX
      XXXX gettext(u'Date') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBBBBBBBBB BB BBBBBBBBBBBB
    XXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB
        XX
        BBBBB
      XXXXX
      XXXXFFFFFFFFFFFXXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      X XXXX BBBBB BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XX XXXXXXXXXXXXX
        XXXXXXXXXX  BB BBBB BB BBB XXXXXXXX XXXXXX BBBBXXXXXXXXXXXXXXXXBBBBBX
        XXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        
    XXXX
    BBBBBB

    BB BBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB

  XXXXXX
XXXXXX
BBBB
 gettext(u'No Sellings yet') 
BBBBB
