BBBB BBBBBBBBBB
BBBB BBBB
BB BBBBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX XXXXX
      XXXX gettext(u'Product') XXXXX
      XXXX gettext(u'Count') XXXXX
      XXXX gettext(u'Price') XXXXX
      XXXX gettext(u'Collaborator') XXXXX
      XXXX gettext(u'Note') XXXXX
      XXXX gettext(u'Date') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBBBBBB BB BBBBBBBBB
    XXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXX XXXXXXXXXXXXX
        
      XXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXFFFFFFFFFFFXXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      X XXXX BBBBB BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XX XXXXXXXXXXXXX
        XXXXXXXXXX  BB BBBB BB BBB XXXXXXXX XXXXXX BBBBXXXXXXXXXXXXXXXXBBBBBX
        XXXXXXXXBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        
    XXXX
    BBBBBB

    BB BBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB

  XXXXXX
XXXXXX
BBBB
 gettext(u'No ransfers yet') 
BBBBB