# Generated by Django 3.2.16 on 2023-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
