# Generated by Django 3.2.16 on 2023-08-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, default='cms.yatuk.am', max_length=255, null=True),
        ),
    ]
