# Generated by Django 3.2.16 on 2023-01-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title English')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Russian')),
                ('title_hy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title Armenian')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_ru', models.TextField(verbose_name='Description Russian')),
                ('description_hy', models.TextField(verbose_name='Description Armenian')),
                ('author_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author English')),
                ('author_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Russian')),
                ('author_hy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Armenian')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/gameimage', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.TextField()),
                ('piece_count', models.PositiveIntegerField(default=35)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.gameimage')),
            ],
        ),
    ]
